name: Build and Deploy
on: 
  push:
  schedule:
      - cron: '0 0 * * *' # Once per day at midnight
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          export GH_USER=${{ secrets.GH_USER }}
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          export DOMAIN=${{ secrets.DOMAIN }}

          sudo apt-get install python3-setuptools
          pip3 install -r requirements.txt
          python3  build.py

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.